version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  build:
    docker:
      - image: circleci/node:erbium
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@5"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-packages
          command: npm install
      - run:
          name: generate spa files
          command: npm run generate
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          cd workspace
          aws s3 sync --cache-control 'max-age=604800' --exclude index.html build/ s3://elijahmcclendon.com/
          aws s3 sync --cache-control 'no-cache' build/ s3://elijahmcclendon.com/
